# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 742ccd59f77629bedc29e2f10c7a0d3fd44fe2eaf5a6d6bb8716676f18f17930dc77c6e751f184b358fb442fb7d4751def8b33cbc39bbc23ef9e932042cc65fa

test:
  secret_key_base: 040dd6b3c8be15d41e25fb0bded12c83b461772384cfbe1a2f8feec9730289329a677c39e2a9e9c08a15ff6a37da6f0cde9af5828d3010822a214c06a602075c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
